export const WEATHER_FETCH_REQUEST = 'WEATHER_FETCH_REQUEST';
export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const WEATHER_FETCH_FAILURE = 'WEATHER_FETCH_FAILURE';
export const GET_CITY_NAME = 'GET_CITY_NAME';
